/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ApiImport } from './routes/_api'
import { Route as IndexImport } from './routes/index'
import { Route as ApiApiImport } from './routes/_api/api'
import { Route as ApiItemsImport } from './routes/_api._items'
import { Route as ApiItemsApiItemsImport } from './routes/_api/_items/api.items'

// Create/Update Routes

const ApiRoute = ApiImport.update({
  id: '/_api',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ApiApiRoute = ApiApiImport.update({
  path: '/api',
  getParentRoute: () => ApiRoute,
} as any)

const ApiItemsRoute = ApiItemsImport.update({
  id: '/_items',
  getParentRoute: () => ApiRoute,
} as any)

const ApiItemsApiItemsRoute = ApiItemsApiItemsImport.update({
  path: '/api/items',
  getParentRoute: () => ApiItemsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_api': {
      id: '/_api'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ApiImport
      parentRoute: typeof rootRoute
    }
    '/_api/_items': {
      id: '/_api/_items'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ApiItemsImport
      parentRoute: typeof ApiImport
    }
    '/_api/api': {
      id: '/_api/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiApiImport
      parentRoute: typeof ApiImport
    }
    '/_api/_items/api/items': {
      id: '/_api/_items/api/items'
      path: '/api/items'
      fullPath: '/api/items'
      preLoaderRoute: typeof ApiItemsApiItemsImport
      parentRoute: typeof ApiItemsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ApiRoute: ApiRoute.addChildren({
    ApiItemsRoute: ApiItemsRoute.addChildren({ ApiItemsApiItemsRoute }),
    ApiApiRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_api"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_api": {
      "filePath": "_api.tsx",
      "children": [
        "/_api/_items",
        "/_api/api"
      ]
    },
    "/_api/_items": {
      "filePath": "_api._items.tsx",
      "parent": "/_api",
      "children": [
        "/_api/_items/api/items"
      ]
    },
    "/_api/api": {
      "filePath": "_api/api.tsx",
      "parent": "/_api"
    },
    "/_api/_items/api/items": {
      "filePath": "_api/_items/api.items.tsx",
      "parent": "/_api/_items"
    }
  }
}
ROUTE_MANIFEST_END */
